UnEtatJeu getEtatJeu()
Integer getTempsMax()
Integer TempsRestant()
void getTempsMaxAlloué()
void setEtatUnEtatMemory()
void setTempsMaxAlloué()
void setTempsRestant()
virtual void getNbCasesOccupées()
virtual void setNbCaseOccupées()
virtual void getNbPairesObtenues()
virtual void setNbPairesObtenues()
